#!/usr/bin/env node
/**
 * Interactive setup wizard for armaraos-discord-bot.
 * Run: npm run setup
 *
 * You only need to paste 3 things from Discord (we explain where):
 *   1. Bot token
 *   2. Application (client) ID
 *   3. Server (guild) ID
 *
 * Everything else is auto-configured via the Discord API.
 */
import { createInterface } from 'node:readline/promises';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const configPath = join(root, 'config', 'default.json');

const rl = createInterface({ input: process.stdin, output: process.stdout });

const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const GREEN = '\x1b[32m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

function log(msg) {
  console.log(msg);
}

function section(title) {
  log(`\n${BOLD}${CYAN}━━ ${title} ━━${RESET}\n`);
}

async function ask(question, defaultValue = '') {
  const hint = defaultValue ? ` ${DIM}(default: ${defaultValue})${RESET}` : '';
  const answer = (await rl.question(`${question}${hint}: `)).trim();
  return answer || defaultValue;
}

async function discordGet(token, path) {
  const res = await fetch(`https://discord.com/api/v10${path}`, {
    headers: { Authorization: `Bot ${token}` },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`${path} → HTTP ${res.status}: ${body.slice(0, 200)}`);
  }
  return res.json();
}

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

function findChannel(channels, ...names) {
  for (const name of names) {
    const n = name.toLowerCase();
    const hit = channels.find(
      (c) => c.name?.toLowerCase() === n || c.name?.toLowerCase().includes(n),
    );
    if (hit) return hit.id;
  }
  return null;
}

function findRole(roles, ...names) {
  for (const name of names) {
    const n = name.toLowerCase();
    const hit = roles.find((r) => r.name?.toLowerCase() === n || r.name?.toLowerCase().includes(n));
    if (hit) return hit.id;
  }
  return null;
}

function writeEnv(vars) {
  const lines = [
    '# Generated by npm run setup',
    `DISCORD_BOT_TOKEN=${vars.token}`,
    `DISCORD_CLIENT_ID=${vars.clientId}`,
    `DISCORD_GUILD_ID=${vars.guildId}`,
    '',
    'NOTIFICATIONS_URL=https://www.ainativelang.com/notifications',
    'DOCS_SEARCH_URL=https://www.ainativelang.com/api/docs/search',
    'DOCS_MANIFEST_URL=https://www.ainativelang.com/search/docs-manifest.json',
    'BLOG_FEED_URL=https://www.ainativelang.com/blog/feed.json',
    'DATABASE_PATH=./data/bot.db',
    'CONFIG_PATH=./config/default.json',
    'AINL_VALIDATE_URL=http://127.0.0.1:8765/validate',
    'ARMARAOS_API_BASE=http://127.0.0.1:4200',
    '',
  ];
  writeFileSync(envPath, lines.join('\n'));
  log(`${GREEN}✓${RESET} Wrote ${envPath}`);
}

function mergeConfig(updates) {
  const config = JSON.parse(readFileSync(configPath, 'utf8'));
  Object.assign(config.channels, updates.channels);
  Object.assign(config.roles, updates.roles);
  if (updates.faq) Object.assign(config.faq, updates.faq);
  writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`);
  log(`${GREEN}✓${RESET} Updated ${configPath}`);
}

function printInviteUrl(clientId) {
  // Send Messages, Embed Links, Read History, Add Reactions, Manage Threads, Use Slash Commands
  const permissions = '274877975552';
  const url = `https://discord.com/api/oauth2/authorize?client_id=${clientId}&permissions=${permissions}&scope=bot%20applications.commands`;
  log(`\n${BOLD}Invite the bot to your server (open this URL):${RESET}`);
  log(url);
  log(`\n${DIM}If the bot is already in your server, skip opening the link.${RESET}\n`);
  return url;
}

async function main() {
  log(`
${BOLD}ArmaraOS Discord Bot — Setup Wizard${RESET}
${DIM}This script configures .env and config/default.json for you.${RESET}
`);

  section('Step 1 — Discord Developer Portal');
  log(`Open: ${BOLD}https://discord.com/developers/applications${RESET}`);
  log('1. Click "New Application" → name it "Armara Community Bot"');
  log('2. Open the Bot tab → "Reset Token" → copy the token');
  log('3. Enable intents: Server Members + Message Content');
  log('4. Open General Information → copy "Application ID" (this is CLIENT_ID)');
  log('');

  const token = await ask('Paste your BOT TOKEN');
  if (!token || token.length < 20) {
    log('Invalid token. Run setup again after creating the bot.');
    rl.close();
    process.exit(1);
  }

  let clientId = await ask('Paste Application ID (CLIENT_ID)');
  if (!clientId) {
    try {
      const app = await discordGet(token, '/oauth2/applications/@me');
      clientId = app.id;
      log(`${GREEN}✓${RESET} Detected Application ID: ${clientId}`);
    } catch {
      log('Could not detect client ID — please paste it manually.');
      rl.close();
      process.exit(1);
    }
  }

  printInviteUrl(clientId);
  await ask('Press Enter after the bot is invited to your Discord server');

  section('Step 2 — Server (Guild) ID');
  log('In Discord desktop app:');
  log('  User Settings → Advanced → enable Developer Mode');
  log('  Right-click your server icon → Copy Server ID');
  log('');

  const guildId = await ask('Paste your SERVER (GUILD) ID');
  if (!guildId) {
    rl.close();
    process.exit(1);
  }

  section('Step 3 — Auto-detecting channels & roles');
  let channels, roles, me;
  try {
    me = await discordGet(token, '/users/@me');
    channels = await discordGet(token, `/guilds/${guildId}/channels`);
    roles = await discordGet(token, `/guilds/${guildId}/roles`);
    log(`${GREEN}✓${RESET} Connected as bot: ${me.username}`);
    log(`${GREEN}✓${RESET} Found ${channels.length} channels, ${roles.length} roles`);
  } catch (err) {
    log(`\nError: ${err.message}`);
    log('\nCommon fixes:');
    log('  • Bot not invited to server — use the invite URL above');
    log('  • Wrong guild ID');
    log('  • Invalid token');
    rl.close();
    process.exit(1);
  }

  const channelMap = {
    welcome: findChannel(channels, 'introductions', 'start-here', 'welcome'),
    releases: findChannel(channels, 'releases', 'announcements'),
    modLog: findChannel(channels, 'mod-log', 'modlog', 'audit'),
    staffSupport: findChannel(channels, 'staff-support', 'staff'),
    communityHighlights: findChannel(channels, 'announcements', 'general', 'community-highlights'),
    showcase: findChannel(channels, 'showcase', 'show-and-tell'),
  };

  const roleMap = {
    staffIds: [findRole(roles, 'staff', 'mod', 'moderator')].filter(Boolean),
    regularId: findRole(roles, 'regular', 'active'),
    contributorId: findRole(roles, 'contributor', 'contributors'),
    announcementsId: findRole(roles, 'announcements', 'news'),
    armaraosUserId: findRole(roles, 'armaraos-user', 'armaraos', 'armara'),
  };

  const helpForum =
    channels.find((c) => c.type === 15 && /help|support/.test(c.name?.toLowerCase() ?? '')) ??
    channels.find((c) => c.type === 15);

  log('\nDetected mapping:');
  for (const [k, v] of Object.entries(channelMap)) {
    const ch = channels.find((c) => c.id === v);
    log(`  channels.${k}: ${v ? `#${ch?.name ?? '?'} (${v})` : '(not found — set in config later)'}`);
  }
  for (const [k, v] of Object.entries(roleMap)) {
    if (k === 'staffIds') {
      log(`  roles.staffIds: ${v.length ? v.join(', ') : '(not found)'}`);
    } else {
      const r = roles.find((x) => x.id === v);
      log(`  roles.${k}: ${v ? `@${r?.name} (${v})` : '(not found)'}`);
    }
  }
  if (helpForum) log(`  faq forum: #${helpForum.name} (${helpForum.id})`);

  const ok = await ask('\nUse this auto-detected config? (Y/n)', 'Y');
  if (ok.toLowerCase() === 'n') {
    log('Edit config/default.json manually after setup.');
  } else {
    mergeConfig({
      channels: channelMap,
      roles: roleMap,
      faq: {
        channelIds: helpForum ? [helpForum.id] : [],
      },
    });
  }

  writeEnv({ token, clientId, guildId });

  section('Step 4 — Register slash commands & database');
  mkdirSync(join(root, 'data'), { recursive: true });
  try {
    execSync('npm run db:migrate', { cwd: root, stdio: 'inherit', env: { ...process.env, DISCORD_BOT_TOKEN: token } });
    execSync('npm run register-commands', { cwd: root, stdio: 'inherit', env: { ...process.env, DISCORD_BOT_TOKEN: token, DISCORD_CLIENT_ID: clientId, DISCORD_GUILD_ID: guildId } });
  } catch {
    log('Command registration failed — run `npm run register-commands` manually.');
  }

  section('Done!');
  log(`${GREEN}Setup complete.${RESET} Start the bot with:\n`);
  log(`  cd ~/Desktop/Projects/armaraos-discord-bot`);
  log(`  npm run dev`);
  log(`\nIn Discord, try: ${BOLD}/ping${RESET}  ${BOLD}/start${RESET}  ${BOLD}/docs query:armaraos install${RESET}`);
  log(`\n${DIM}Missing channels? Create them using docs/SERVER_TEMPLATE.md then re-run npm run setup${RESET}\n`);

  rl.close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
